apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry-deployment
  template:
    metadata:
      labels:
        app: service-registry-deployment
    spec:
      containers:
      - name: service-registry-deployment
        image: soumiknandi/service-registry   
        ports:
        - containerPort: 8761
        env:
        - name : SPRING_PROFILES_ACTIVE
          value : docker