apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-auth-pvc
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi