apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-auth-statefulset
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-auth-statefulset
  template:
    metadata:
      labels:
        app: mongodb-auth-statefulset
    spec:
      containers:
      - name: mongodb-auth-container
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-auth-persistent-storage
      volumes:
      - name: mongodb-auth-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-auth-pvc