apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service-deployment
  template:
    metadata:
      labels:
        app: auth-service-deployment
    spec:
      containers:
      - name: soumiknandi-auth-service
        image: soumiknandi/auth-service:latest
        ports:
        - containerPort: 8089
        env:
        - name : SPRING_PROFILES_ACTIVE
          value : docker