apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-movie-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mariadb-movie