apiVersion: v1
kind: Service
metadata:
  name: maria-db-movie
spec:
  type: NodePort
  selector:
    app: mariadb-movie-statefulset
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30003