apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service-deployment
  template:
    metadata:
      labels:
        app: movie-service-deployment
    spec:
      containers:
      - name: soumiknandi-movie-service
        image: soumiknandi/movie-service:latest
        ports:
        - containerPort: 8081
        env:
        - name : SPRING_PROFILES_ACTIVE
          value : docker