eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
spring:
  datasource:
    password: password
    username: root
    url: jdbc:mysql://maria-db-movie:3306/movie