apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artist-service-deployment
  template:
    metadata:
      labels:
        app: artist-service-deployment
    spec:
      containers:
      - name: soumiknandi-artist-service
        image: soumiknandi/artist-service:latest
        ports:
        - containerPort: 8082
        env:
        - name : SPRING_PROFILES_ACTIVE
          value : docker